### ISSUE TITLE
Tapping Directions to ULB in map screen opens location in England in GPS app

### ISSUE THREAD

**Issue by TheLastProject** [cbeyls/fosdem-companion-android#12]
According to my info, FOSDEM is in Brussels in January. I'm also not sure what ULB mean, why not just name the button "Directions"?

**Comment by cbeyls** [comment]
ULB is the name of the university where FOSDEM takes place in Brussels.
Which GPS app are you using, on which device and Android version? The passed URL is known to work with the latest Google Maps app or with any web browser.

**Comment by TheLastProject** [comment]
I'm using OsmAnd~ 2.2.4 from F-Droid. Notably, it opens a GPS location with Lat: 50.812375 and Lon: 0.0 when pressing on it, so it probably misparses the location.

I have tested this with the Google Maps webpage by opening it with Fennec, which parses it correct. Curiously enough, if I open it in Fennec first, and use the built-in function to give it to a native app then, it works correctly, so seemingly the Google Maps website rewriting the URL makes OsmAnd able to parse it.

If it doesn't break any existing map software, could you consider switching `http://maps.google.com/maps?f=d&daddr=%1$f,%2$f(%3$s)&dirflg=r` [in your MapFragment.java String.format](https://github.com/cbeyls/fosdem-companion-android/blob/29d923a1cde43bf152fc816907e0b835cc16b42a/app/src/main/java/be/digitalia/fosdem/fragments/MapFragment.java#L53) to `https://www.google.com/maps/dir//%1$f,%2$f/`? This seems to fix OsmAnd and doesn't break the online map URL. Unfortunately, I cannot test it with the official Google Maps app, as I do not have it installed.

**Comment by cbeyls** [comment]
I'm using dirflg=r to setup Google Maps directions in public transport mode and I don't know how to do that with the new URL scheme. However I found the cause of the issue by looking at OsmAnd's code.
