### ISSUE TITLE
Feature: Add Room Video Link for vlc

### ISSUE THREAD

**Issue by jkahrs** [cbeyls/fosdem-companion-android#13]

**Comment by cbeyls** [comment]
Links to videos are progressively added after FOSDEM as standard links and handled by the browser or other applications like VLC, so I believe this is already working as you expect.

**Comment by jkahrs** [comment]
Sorry for being late here. :)

Last year there were live stream URLs for (at least) some rooms so people were able to watch a talk even if the room was full/closed.

I'm not sure where those were meant to appear as I found the live URL for the golang room via twitter.

**Comment by cbeyls** [comment]
Thank you for providing more information.
The app data comes exclusively from the schedule XML file. I'm afraid the live video streams URLs can not be inferred from the data in that file. But I can add a link to the "live.fosdem.org" web site in the app.

**Comment by jkahrs** [comment]
Sounds good.

Do you know if the room number is always appended similarly to the following schemes (Room H.1302)?
- live.fosdem.org: "/watch.php?room=h1302"
- stream-a.fosdem.org:8080 : "/fosdem+h1302cam.flv"

This way the link could go directly from the track overview to the correct section. Maybe somebody from the FOSDEM team sees this and can propose an update to the XML.

Also I can't remember exactly if live.fosdem.org was compatible with Chrome on Android. I'll check this next time. ;)

**Comment by cbeyls** [comment]
I think some room names for live streams are longer than the room names in XML. And not every room has a live stream.
I'll try to reach someone from the FOSDEM team for more info.

**Comment by cbeyls** [comment]
The FOSDEM team added a direct link to the live video in the schedule data. The app shows it at the bottom of the talk description.
