### ISSUE TITLE
Bullet points not rendered

### ISSUE THREAD

**Issue by lucaceresoli** [cbeyls/fosdem-companion-android#14]
The talk abstract and description allow [some markup](http://daringfireball.net/projects/markdown/syntax#list), e.g. bullet points. Some talks are using it, e.g. [this one](https://archive.fosdem.org/2016/schedule/event/flow/).

This markup (at least bullet points, that's what I noticed) is rendered correctly on the fosdem website. The app does not render them at all, and all lines are concatenated on a single line without spaces. It would be great if they were rendered correctly.

Except for this, a great app, thanks!

**Comment by cbeyls** [comment]
Thank you for your input; the feature will be in the next release.
