### ISSUE TITLE
SearchView disappear on orientation change

### ISSUE THREAD

**Issue by reverse-unina** [cbeyls/fosdem-companion-android#16]
When I perform these sequences of events, the search widget disappear and looses user input:

Sequence 1:
1. Click on Search icon
2. Enter Text
3. Orientation Change

**Comment by cbeyls** [comment]
SearchView used as an action view inside a collapsed menu item does not have its state saved or restored automatically like normal views. But this can be done manually with some hacks.

**Comment by cbeyls** [comment]
After consideration, I'll not implement this custom behavior. This might change in the future if Google provides a new standardized search widget.
