### ISSUE TITLE
Action Overflow Menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [cbeyls/fosdem-companion-android#18]
When i perform this sequence of events, the menu disappears:

1. Open Side Drawer
2. Click on Bookmarks
3. Click on ... (More Options)
4. Orientation Change

**Comment by cbeyls** [comment]
Menu items are re-organized after orientation change. There is more room for items in landscape mode than in portrait mode for example so if an overflow menu is no longer needed (when all items can be displayed in the app bar) it disappears. All apps do that AFAIK.
