### ISSUE TITLE
nav.fosdem.org integration

### ISSUE THREAD

**Issue by markvdb** [cbeyls/fosdem-companion-android#21]
Hello cbeyls,

Mark here, FOSDEM staff. Really cool to see you have updated this one for FOSDEM 2017 too.

I wonder if you see a way to integrate or give some extra visibility to nav.fosdem.org. That is an on-campus routing app. Experimental for now, finishing touches, but we are rather certain it will be production ready by FOSDEM. It's basicly the FOSDEM campus data ported to the official 33c3 routing app.

One can do things like find the way to a specific stand or devroom in the app. In a future iteration, we might also be able to detect position based on ssids and similar stuff.

If you're interested, we can be reached at irc.freenode.net#fosdem-nav to speak about this in a less asynchronuous way. Kragniz is the person leading this effort.

Kind regards,

Mark

**Comment by cbeyls** [comment]
Hello, I mainly maintain the app to clean up code and follow the latest Android trends. I didn't do anything special for the 2017 edition of FOSDEM.
I did not have a chance to test nav.fosdem.org (it looks down today) but it surely looks interesting.
Ideally you could provide a URL to compute the destination from the current location to a specific room so I can add a button or link in the event details screen.

**Comment by cbeyls** [comment]
If that kind of integration is not possible I can simply add a button to the "campus map" screen to open nav.fosdem.org

**Comment by cbeyls** [comment]
Released to production

**Comment by cbeyls** [comment]
Unfortunately integration was worse this year because many room ids in the nav app have changed. The room ids used in URLs need to follow a strict naming convention in order for the app to be able to build the correct URL to the nav app with the target room pre-filled. Alternatively, an extra field in the XML data could provide the room id to be used to build the URL to the nav app.
