### ISSUE TITLE
Add feature to rate the talks

### ISSUE THREAD

**Issue by fredg02** [cbeyls/fosdem-companion-android#26]
Please make it easier to rate talks, because only a few people will go back to the website to give feedback.

**Comment by cbeyls** [comment]
Right now there is a "Send feeback" link below every talk description which links to the website. I don't want to spam users with popups either. To make the feedback process easier you may want to make the website more responsive so the UI is better suited to phones.

**Comment by fredg02** [comment]
Sure, nobody wants popups. I actually meant just having the feedback form in the app instead of just a link to the website. I don't know if the forms could be filled with a REST API or something similar though. If not, it would require some changes on the FOSDEM website as well.

**Comment by cbeyls** [comment]
The app can call a REST API, but if you use reCAPTCHA to prevent spamming the web form, you also need to provide a way to prevent spamming the API.

**Comment by cbeyls** [comment]
I added a dedicated "Submit feedback" button in 212faa8d7c44180757d8d72214f609cb859df166
This button is tied to `feedback_url`, a new field in the XML data.

**Comment by fredg02** [comment]
Thanks for adding the feedback button. It took a while 😆, but it is still very much appreciated.
