### ISSUE TITLE
red "full room" and green "not full" room text is not accessible for those with colour blindness 

### ISSUE THREAD

**Issue by yamatt** [cbeyls/fosdem-companion-android#32]
The notification for rooms being full is a really great feature, but is completely invisible for those with red-green colour blindness.

**Comment by cbeyls** [comment]
Yes I'm fully aware of it. I had to implement the feature in a rush and though showing the status text in the detail page was enough. For next year the app will probably display an icon next to the room name in the lists.

**Comment by cbeyls** [comment]
I updated the content description in lists in version 1.5.1. I'll add the display of some icon when the room is full in a future release.
