### ISSUE TITLE
Compare bookmarks beetween friends

### ISSUE THREAD

**Issue by pmalhaire** [cbeyls/fosdem-companion-android#41]
It will be nice to know if a friend is going to the same talks.

A way to do that is to be able to compare my bookmarks with an ics file.

ie. 
1. I click on compare with on my bookmark page.
2. I choose my friend bookmarks ics file.
3. It shows the talks we both are going to.

**Comment by cbeyls** [comment]
Thank you for the suggestion. I think I'll implement this using NFC sharing between Android phones.

**Comment by pmalhaire** [comment]
Your solution is better, I tried to think about how to do the trick in a minimal maner.
