### ISSUE TITLE
The widgets on the action bar disapper after a series of operations about searching events

### ISSUE THREAD

**Issue by junior291492659** [cbeyls/fosdem-companion-android#47]
Hello,

- I have searched the history bug list, and have not found a similar bug.

- The bug was found on the latest version 1.6.2 on google play (can be reproduced on an Android emulator 6.0 and a Redmi Note 4X phone )

- Bug: I install the version 2.3.5 and start the app, open the drawer menu, click Bookmarks, it get us to the 'Bookmarks' page and there are two widgets on the left of  the dot menu(upper right) on the action bar, then click the dot menu, click Search events, and click the dot menu again, click Search events again, finally click the 'back' icon(upper left) on the action bar, the two previous widgets disappear.
Only after I open the drawer menu, go to other page and return to the 'Bookmarks' page can the two  widgets show again. Noted that the second click of dot menu and Search events before the click of the 'back' icon is necessary for triggering this disappearance.

- Reproducing video: [https://youtu.be/3mbutkGL7BI](https://youtu.be/3mbutkGL7BI)

It would be really appreciated to get your concern on this. Thanks!

**Comment by cbeyls** [comment]
Thank you for your report. This looks like a bug present in all recent versions of AppCompat, related to collapsible action views. I will implement a workaround.

**Comment by junior291492659** [comment]
Thanks for your quick reply and fix : )
