### ISSUE TITLE
Ability to view or export favorite talks as a timetable

### ISSUE THREAD

**Issue by bparmentier** [cbeyls/fosdem-companion-android#5]
Thanks for this useful app!

Would be cool to have a timetable with the favorite talks, so that you have a better overview to make a choice between the overlapping talks and those you can attend.

Today I also used the Giggity app to solve this problem: import the schedule and remove all unwanted talks…

**Comment by dfandrich** [comment]
Exporting favourite talks would be extremely useful. I would also use it as a diary of what talks I attended, as well as a reminder of what talks would be worth virtually attending afterward by viewing the recording. There seems to be no way currently to get this user-entered data out of the phone. I could envisage this as being implemented through a *Share* function (sharing a calendar of some sort with another app) or as an iCalendar dump on SD card or into Google Drive.

**Comment by cbeyls** [comment]
I started implementing a feature to export bookmarks to an iCalendar file.
