### ISSUE TITLE
Error updating schedule

### ISSUE THREAD

**Issue by jsoriano** [cbeyls/fosdem-companion-android#63]
First of all, thanks for this app! It has been for some years my app of choice to organize the complicated FOSDEM schedules :slightly_smiling_face: 

It was also working with the 2021 schedule, but since some days ago the app is failing to update schedule.

It shows a message with this error: `An error occured during schedule update. Check your device connection.`. And a retry button.

The schedule URL (https://fosdem.org/schedule/xml) referenced [here](https://github.com/cbeyls/fosdem-companion-android/blob/4e8959ce843fd00cbfa5c683dd01097f0c2c5078/app/src/main/java/be/digitalia/fosdem/api/FosdemUrls.kt#L11) seems to work, but maybe the format has changed?

Is this a known issue?

**Comment by jsoriano** [comment]
I see this error in logcat:
```
01-23 12:25:02.387  4539  4631 W System.err: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: events_persons.event_id, events_persons.person_id (code 1555)
01-23 12:25:02.387  4539  4631 W System.err: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-23 12:25:02.387  4539  4631 W System.err: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
01-23 12:25:02.387  4539  4631 W System.err: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
01-23 12:25:02.388  4539  4631 W System.err: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
01-23 12:25:02.388  4539  4631 W System.err: 	at w.u.a.i.i.a()
01-23 12:25:02.388  4539  4631 W System.err: 	at x.a.a.f.y0.a(:35)
01-23 12:25:02.388  4539  4631 W System.err: 	at x.a.a.f.y0.a(:86)
01-23 12:25:02.388  4539  4631 W System.err: 	at x.a.a.e.h.b(:8)
01-23 12:25:02.388  4539  4631 W System.err: 	at z.s.m.a.a.a()
01-23 12:25:02.388  4539  4631 W System.err: 	at a0.a.p0.run(:2)
01-23 12:25:02.388  4539  4631 W System.err: 	at a0.a.o2.d.a()
01-23 12:25:02.388  4539  4631 W System.err: 	at a0.a.o2.b.run(:7)
```
A person is assigned to the same event twice?

**Comment by jsoriano** [comment]
> A person is assigned to the same event twice?

Actually person with id `8221` is duplicated in event `11747`: https://fosdem.org/2021/schedule/event/infrastructure_as_code_drifts_arent_like_pokemon_you_cant_catch_em_all/

**Comment by cbeyls** [comment]
Hello, thanks for the report!
Looks like there was indeed some invalid data in the XML (duplicate person entry for the same event), but it's now fixed.
I'll merge your pull request anyway in case this happens again.
