### ISSUE TITLE
Timezone Awareness

### ISSUE THREAD

**Issue by oxr463** [cbeyls/fosdem-companion-android#66]
It would be nice if the times were localized, e.g., to EST.

**Comment by cbeyls** [comment]
The schedule data is not timezone-aware so the timezone is currently hardcoded for the conference and the same one is used everywhere.
I'll investigate how I can add the timezone on the talk details screen for clarity.

**Comment by cbeyls** [comment]
Times could be displayed using the local timezone, but it would be confusing for users traveling to attend the physical conference and changing timezones. Or maybe I can make it an option in the settings.

**Comment by oxr463** [comment]
> The schedule data is not timezone-aware so the timezone is currently hardcoded for the conference and the same one is used everywhere.

Oh I didn't realize that.

**Comment by oxr463** [comment]
> Times could be displayed using the local timezone, but it would be confusing for users traveling to attend the physical conference and changing timezones. Or maybe I can make it an option in the settings.

Yes, perhaps an option in settings would help.

If I have my timezone (EST) set properly on my Android phone, and I travelled to the conference physically; my phone would update itself to the local timezone.

Is there an API in Android that exposes the current local timezone?

**Comment by cbeyls** [comment]
> Is there an API in Android that exposes the current local timezone?

Yes, you can call `TimeZone.getDefault()` to get the current local timezone. By default, the phone updates it automatically according to the phone network information. Java Date formatters also use the local timezone by default. In this app I currently override this with the conference timezone.
So it would just be a matter of selecting the default timezone or the conference timezone for dates display according to user preference.

**Comment by Findus23** [comment]
I am currently trying to adapt this app to MatomoCamp and this is something I am interested in as the event is online and everyone uses the app therefore in their local time zone.

I created this quick change that seems to work correctly: https://github.com/MatomoCamp/matomocamp-companion-android/commit/474988451ce87500dcce22b4638180302df08e85

But keep in mind that I am not an Android developer and I haven't tested it extensively.

**Comment by cbeyls** [comment]
> I am currently trying to adapt this app to MatomoCamp and this is something I am interested in as the event is online and everyone uses the app therefore in their local time zone.
> 
> I created this quick change that seems to work correctly: [MatomoCamp@4749884](https://github.com/MatomoCamp/matomocamp-companion-android/commit/474988451ce87500dcce22b4638180302df08e85)
> 
> But keep in mind that I am not an Android developer and I haven't tested it extensively.

I took a look at your pull request and left some comments. Overall, the logic looks OK but I found a few issues.

In a future pull request of FOSDEM Companion, I'm going to switch all the date/time logic to the `java.time` APIs.
Also, I will probably use dependency injection to inject the display `TimeZone` in the Activity and make sure the same instance is reused in the same activity. This way, the code which determines which timezone to use will be centralized in the dependency injection configuration.

**Comment by Findus23** [comment]
Just FYI, I didn't intend this as a pull request (as I don't think my Android skills are good enough for the code to be used as-is), but is just one commit on my fork.
But many thanks for taking a look at my changes.

And while I got the chance also a huge thank you for providing this app as Open Source. It was a lot of fun adapting it to the MatomoCamp needs even though I hardly ever worked with Android apps before.

**Comment by cbeyls** [comment]
FYI I changed a lot of code related to date and time formatting recently and I'm now working on adding this feature
