### ISSUE TITLE
Feature: Import/export starred events

### ISSUE THREAD

**Issue by adriaaah** [cbeyls/fosdem-companion-android#67]
I think it would be a nice feature to make backups but also to share the entire list of tracks one would try to attend.

**Comment by cbeyls** [comment]
These two features are already implemented (export has been implemented 2 years ago and I added import yesterday).

You'll find the "export bookmarks" and "import bookmarks" buttons on the bookmarks screen. The app will create a file in iCalendar format so it can be imported into your favourite calendar app.

**Comment by adriaaah** [comment]
Ouch, I haven't noticed that arrow did it. Thank you and I hope you keep enjoying FOSDEM.
