### ISSUE TITLE
Change 'upcoming only' to 'upcoming and ongoing'?

### ISSUE THREAD

**Issue by hrw** [cbeyls/fosdem-companion-android#78]
I have a lot of conflicts in my bookmarks. During online FOSDEM it is less problematic as there is no need to walk between rooms/buildings.

When I watch session X which ends at 15:30 I want to switch to one which is 15:20 - 16:00. But as is 'ongoing' session it is not displayed in Bookmarks view anymore.

What do you think about doing such change?

**Comment by cbeyls** [comment]
I changed the feature name to "hide past sessions". The meaning is easier to understand, and sessions in progress will now always be shown.
