### ISSUE TITLE
Remember scroll state

### ISSUE THREAD

**Issue by keunes** [cbeyls/fosdem-companion-android#81]
After making a first selection for my programme, I go through the list of bookmarks to plan where I actually go. As the physical aspect is important also, I sometimes have to quickly see the map to remember and check if I can make it between talks. However, when going back to the Bookmarks list my scroll position is lost.

It would be great if the scroll position can be maintained when switching between screens, so I can quickly continue 'compiling' my programme after checking the map.

**Comment by cbeyls** [comment]
This will be added to the next release, as it's trivial to implement.
